/**
 * Writes the logo print master from lib/brand/logo-geometry.ts and lib/pdf/fonts/Jost.ttf:
 *   public/brand/logo-master.pdf — for people (designers, printers)
 *   lib/brand/logo-master.ts     — the same bytes as base64, which every generated PDF embeds
 *     (the server bundle carries it, so nothing reads a file at runtime).
 * tests/brand/logo-master.test.ts pins the file: after a deliberate change, look at the PDF, then update its hash.
 *
 * Usage: npx -y tsx scripts/build-logo-master.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { buildLogoMaster } from "../lib/brand/build-logo-master";

async function main() {
  const bytes = await buildLogoMaster(new Uint8Array(readFileSync("lib/pdf/fonts/Jost.ttf")));
  writeFileSync("public/brand/logo-master.pdf", bytes);
  const lines = Buffer.from(bytes).toString("base64").match(/.{1,100}/g) ?? [];
  writeFileSync("lib/brand/logo-master.ts", [
    "// Generated by scripts/build-logo-master.ts. Do not edit by hand; tests/brand/logo-master.test.ts pins it.",
    "// The Premier Shade Solutions logo: page 1 the lockup, page 2 the mark. Wordmark outlines from Jost (SIL OFL 1.1, lib/pdf/fonts/Jost-OFL.txt).",
    "export const LOGO_MASTER_PDF_BASE64 = [",
    ...lines.map((line) => `  "${line}",`),
    '].join("");',
    "",
  ].join("\n"));
  console.log(`wrote public/brand/logo-master.pdf and lib/brand/logo-master.ts (${bytes.length} bytes)`);
}

void main();
